### ISSUE TITLE
when to release source code

### ISSUE THREAD

**Issue by xtdx** [urbaninfolab/ComputeGPT#1]
Great job!
When will you release soucr code and training data?
How to clean and fintune prompts? Is there another large model to do that?

**Comment by ryanhlewis** [comment]
Hi there @xtdx ,

I'm overhauling the website in order to include a drop-in API via the Settings menu, so that the general architecture can remain, while one may switch out the code generation backend to anything they want (CodeT5, GPT-4, etc).

![image](https://github.com/urbaninfolab/ComputeGPT/assets/76540311/2956aac4-9de7-408f-b21b-021225329a2d)

Also throwing together a generalized unit test so that when fine-tuning prompts, we can see how much of an improvement we can make, and also know if we accidentally overwrite some previous result, say some prompt was able to accurately generate the answer of "derivative of 2x" before but with some more fine-tuning, it's unable to.

No specific deadline of this, but I'll try to have it out by the end of the week.

As for actually cleaning and fine-tuning, right now we only use simple RegEx and logic to determine what a sentence is about. The most obvious example of this is the following:

"What's the derivative of 5x?" -> usually generates terrible code, especially if the number 5 -> infinity

However, if we instead look for the word "derivative", we know that the best library in Python for derivatives is SymPy.
So, we condition and prompt the following:

"What's the derivative of 5x **using sympy.diff()** ?

Obviously, this is a very trivial example. For the most part, although, recognizing specific operations, like "system of equations" or "matrix" or "volume" allows us to fine-tune for the specific library or appropriate function and achieve state-of-the-art results, especially in terms of answering these numerical problems.

**Comment by xtdx** [comment]
Thanks

**Comment by Coo1frog** [comment]
Didn't want open a new issue, however wanted to check in and ask if you were still going to release the source code and what was the estimated timeline? Thanks in advance.
